apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  template:
    spec:
      containers:
      - name: axp-admin
        image: nagagogulan/axp-admin:tagname  # Update the image tag
        resources:
          limits:
            memory: '512Mi'
            cpu: '250m'
