apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-deployment
spec:
  template:
    spec:
      containers:
      - name: axp-merchant
        image: nagagogulan/axp-merchant:tagname  # Update the image tag
        resources:
          limits:
            memory: '512Mi'
            cpu: '250m'
