apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: merchant
        image: merchant:prod
        resources:
          limits:
            memory: '1Gi'
            cpu: '500m'
