apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080  # Port exposed on the node
  type: NodePort