apiVersion: v1
kind: Service
metadata:
  name: merchant-service
  labels:
    app: merchant
spec:
  selector:
    app: merchant
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
    nodePort: 30090  # Port exposed on the node
  type: NodePort